postgres_project:
  outputs:
    dev:
      dbname: airflow
      host: postgres
      pass: postgres
      port: 5432
      schema: raw
      threads: 1
      type: postgres
      user: postgres
  target: dev
