version: 1

models:
  - name: sources_products
    description: clean table products
    columns:

      - name: product_id
        description: primary key
        tests:
          - unique
          - not_null

      - name: product_name
        test:
          - not_null

      - name: price
        test:
          - is_number

